platform :ios, '6.0'
                
pod 'DOUFoundation',       '~> 0.1.2'
pod 'DoubanObjCClient',    '~> 1.1.2'
pod 'DOUUserManager',      '~> 1.0.0'
pod 'SDWebImage',          '~> 3.5.0'
pod 'iToast',              '~> 0.0.1'
pod 'DOUBugReporter',      '~> 1.1.2'
pod 'YAUIKit',             '~> 1.0.2'
pod 'MBProgressHUD',       '~> 0.8'
pod 'FLKAutoLayout',       '~> 0.1.1'
